Repository Busan-Dinosaur/FoodBowl-Server, pull requests merged in 2023-01, with the labels that each got.

#4 Feature/#3 Test에서도 Lombok을 사용할 수 있도록 한다.
  build.gradle
  src/main/resources/config/application.yml
Labels: 🗞️ chore, ✏️ test

#21 Feature/#5 user 테이블 설계
  src/main/java/com/dinosaur/foodbowl/FoodbowlApplication.java
  src/main/java/com/dinosaur/foodbowl/domain/thumbnail/entity/Thumbnail.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dao/UserRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/User.java
  src/main/java/com/dinosaur/foodbowl/global/entity/BaseEntity.java
  src/test/java/com/dinosaur/foodbowl/domain/user/dao/UserRepositoryTest.java
  src/test/java/com/dinosaur/foodbowl/global/dao/RepositoryTest.java
Labels: 🚀 feature, 🕋 backend

#32 Feature/#14 Rest Docs 를 사용하기 위해 관련 설정을 진행한다.
  .gitignore
  build.gradle
  src/test/java/com/dinosaur/foodbowl/global/api/IntegrationTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parts.snippet
Labels: 🗞️ chore, 🕋 backend

#33 Feature/#6 Follow 테이블을 설계한다.
  src/main/java/com/dinosaur/foodbowl/domain/follow/dao/FollowRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/follow/entity/Follow.java
  src/test/java/com/dinosaur/foodbowl/domain/follow/dao/FollowRepositoryTest.java
Labels: 🚀 feature, 🕋 backend

#34 Feature/#8 Store 테이블을 설계한다.
  src/main/java/com/dinosaur/foodbowl/domain/address/entity/Address.java
  src/main/java/com/dinosaur/foodbowl/domain/category/entity/Category.java
  src/main/java/com/dinosaur/foodbowl/domain/store/dao/StoreRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/store/entity/Store.java
Labels: 🚀 feature, 🕋 backend

#37 Feature/#9 Address 테이블을 설계한다.
  src/main/java/com/dinosaur/foodbowl/domain/address/dao/AddressRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/address/entity/Address.java
Labels: 🚀 feature, 🕋 backend

#38 Feature/#10 Photo 테이블을 설계한다.
  src/main/java/com/dinosaur/foodbowl/domain/photo/dao/PhotoRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/photo/entity/Photo.java
Labels: 🚀 feature, 🕋 backend

#39 Feature/#12 Comment 테이블을 설계한다.
  src/main/java/com/dinosaur/foodbowl/domain/comment/dao/CommentRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/comment/entity/Comment.java
Labels: 🚀 feature, 🕋 backend

#40 Feature/#13 Clip 테이블을 설계한다.
  src/main/java/com/dinosaur/foodbowl/domain/clip/dao/ClipRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/clip/entity/Clip.java
Labels: 🚀 feature, 🕋 backend

#42 Feature/#41 Category 테이블을 설계한다.
  src/main/java/com/dinosaur/foodbowl/domain/category/dao/CategoryRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/category/entity/Category.java
Labels: 🚀 feature, 🕋 backend

#36 Feature/#7 Post 테이블을 설계한다.
  src/main/java/com/dinosaur/foodbowl/domain/post/dao/PostRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/post/entity/Post.java
  src/main/java/com/dinosaur/foodbowl/global/entity/BaseEntity.java
  src/test/java/com/dinosaur/foodbowl/domain/follow/dao/FollowRepositoryTest.java
Labels: 🚀 feature, 🕋 backend

#35 Feature/#28 썸네일 저장하는 기능을 구현한다.
  src/main/java/com/dinosaur/foodbowl/domain/thumbnail/entity/Thumbnail.java
  src/main/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailConstants.java
  src/main/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailFileUtil.java
  src/main/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailInfoDto.java
  src/main/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailType.java
  src/main/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailUtil.java
  src/main/java/com/dinosaur/foodbowl/global/util/thumbnail/exception/ThumbnailException.java
  src/test/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailFileUtilTest.java
  src/test/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailInfoDtoTest.java
  src/test/resources/images/fakeImage.png
  src/test/resources/images/testImage_210x210.png
Labels: 🚀 feature, 🕋 backend

#44 Feature/#43 필요한 Entity를 Import 하고, Column 최대 길이를 명시적으로 나타낸다.
  src/main/java/com/dinosaur/foodbowl/domain/address/entity/Address.java
  src/main/java/com/dinosaur/foodbowl/domain/clip/entity/Clip.java
  src/main/java/com/dinosaur/foodbowl/domain/comment/entity/Comment.java
  src/main/java/com/dinosaur/foodbowl/domain/photo/entity/Photo.java
  src/main/java/com/dinosaur/foodbowl/domain/store/entity/Store.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/User.java
Labels: ⛏️ refactor, 🕋 backend

#46 Feature/#15 회원 가입 및 탈퇴 기능을 구현한다.
  build.gradle
  src/docs/foodbowl.adoc
  src/docs/user/user.adoc
  src/main/java/com/dinosaur/foodbowl/domain/thumbnail/dao/ThumbnailRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/thumbnail/entity/Thumbnail.java
  src/main/java/com/dinosaur/foodbowl/domain/user/api/UserController.java
  src/main/java/com/dinosaur/foodbowl/domain/user/application/DeleteAccountService.java
  src/main/java/com/dinosaur/foodbowl/domain/user/application/SignUpService.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dao/RoleRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dao/UserFindDao.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dao/UserRoleRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dto/response/SignUpResponseDto.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/User.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/role/Role.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/role/UserRole.java
  src/main/java/com/dinosaur/foodbowl/domain/user/exception/UserNotFoundException.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/CustomAccessDeniedHandler.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/JwtTokenProvider.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/JwtUserEntity.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/JwtValidationType.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/SecurityConfiguration.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/TokenValidationDto.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/exception/EmptyJwtException.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/exception/WrongFormatJwtException.java
  src/main/java/com/dinosaur/foodbowl/global/util/auth/AuthUtil.java
  src/main/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailFileUtil.java
  src/main/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailInfoDto.java
  src/main/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailType.java
  src/test/java/com/dinosaur/foodbowl/domain/user/api/UserControllerTest.java
  src/test/java/com/dinosaur/foodbowl/domain/user/dao/RoleRepositoryTest.java
  src/test/java/com/dinosaur/foodbowl/domain/user/dao/UserRepositoryTest.java
  src/test/java/com/dinosaur/foodbowl/global/api/IntegrationTest.java
  src/test/java/com/dinosaur/foodbowl/global/config/security/JwtTokenProviderTest.java
  src/test/java/com/dinosaur/foodbowl/global/dao/RepositoryTest.java
  src/test/resources/images/testImage_1x1.png
Labels: 🚀 feature, 🕋 backend

#51 Feature/#48 DB 수정 사항을 바탕으로 Entity를 수정한다.
  src/main/java/com/dinosaur/foodbowl/domain/address/entity/Address.java
  src/main/java/com/dinosaur/foodbowl/domain/category/entity/Category.java
  src/main/java/com/dinosaur/foodbowl/domain/clip/entity/Clip.java
  src/main/java/com/dinosaur/foodbowl/domain/comment/entity/Comment.java
  src/main/java/com/dinosaur/foodbowl/domain/follow/entity/Follow.java
  src/main/java/com/dinosaur/foodbowl/domain/photo/entity/Photo.java
  src/main/java/com/dinosaur/foodbowl/domain/post/entity/Post.java
  src/main/java/com/dinosaur/foodbowl/domain/store/entity/Store.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/User.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/role/Role.java
  src/test/java/com/dinosaur/foodbowl/domain/category/entity/CategoryTest.java
Labels: ⛏️ refactor, 🕋 backend

#56 Feature/#50 회원 가입 시 각 필드에 제약사항을 적용한다.
  src/main/java/com/dinosaur/foodbowl/domain/user/api/UserController.java
  src/main/java/com/dinosaur/foodbowl/domain/user/application/signup/SignUpService.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dao/UserFindDao.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dao/UserRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/com/dinosaur/foodbowl/domain/user/exception/UserErrorCode.java
  src/main/java/com/dinosaur/foodbowl/domain/user/exception/UserException.java
  src/main/java/com/dinosaur/foodbowl/domain/user/exception/UserExceptionAdvice.java
  src/main/java/com/dinosaur/foodbowl/domain/user/exception/UserNotFoundException.java
  src/main/java/com/dinosaur/foodbowl/global/error/ErrorResponse.java
  src/test/java/com/dinosaur/foodbowl/domain/user/api/UserControllerTest.java
  src/test/java/com/dinosaur/foodbowl/global/api/ControllerTest.java
Labels: 🚀 feature, 🕋 backend

#58 Feature/#17 프로필 수정하는 기능을 구현한다.
  src/docs/user/user.adoc
  src/main/java/com/dinosaur/foodbowl/domain/user/api/UserController.java
  src/main/java/com/dinosaur/foodbowl/domain/user/application/DeleteAccountService.java
  src/main/java/com/dinosaur/foodbowl/domain/user/application/UpdateProfileService.java
  src/main/java/com/dinosaur/foodbowl/domain/user/application/signup/SignUpService.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dto/request/UpdateProfileRequestDto.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/User.java
  src/main/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailUtil.java
  src/main/java/com/dinosaur/foodbowl/global/util/validator/image/ImageFileValidator.java
  src/main/java/com/dinosaur/foodbowl/global/util/validator/image/ImageOrNull.java
  src/test/java/com/dinosaur/foodbowl/domain/user/api/UserControllerTest.java
  src/test/java/com/dinosaur/foodbowl/domain/user/dao/UserRepositoryTest.java
Labels: 🚀 feature, 🕋 backend

#62 Feature/#61 스프링 부트와 자바 버전을 변경한다.
  build.gradle
  src/docs/user/user.adoc
  src/main/java/com/dinosaur/foodbowl/domain/address/entity/Address.java
  src/main/java/com/dinosaur/foodbowl/domain/category/entity/Category.java
  src/main/java/com/dinosaur/foodbowl/domain/clip/entity/Clip.java
  src/main/java/com/dinosaur/foodbowl/domain/comment/entity/Comment.java
  src/main/java/com/dinosaur/foodbowl/domain/follow/entity/Follow.java
  src/main/java/com/dinosaur/foodbowl/domain/photo/entity/Photo.java
  src/main/java/com/dinosaur/foodbowl/domain/post/entity/Post.java
  src/main/java/com/dinosaur/foodbowl/domain/store/entity/Store.java
  src/main/java/com/dinosaur/foodbowl/domain/thumbnail/entity/Thumbnail.java
  src/main/java/com/dinosaur/foodbowl/domain/user/api/UserController.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/User.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/role/Role.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/role/UserRole.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/CustomAccessDeniedHandler.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/JwtTokenProvider.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/SecurityConfiguration.java
  src/main/java/com/dinosaur/foodbowl/global/entity/BaseEntity.java
  src/main/java/com/dinosaur/foodbowl/global/util/auth/AuthUtil.java
  src/main/java/com/dinosaur/foodbowl/global/util/validator/image/ImageFileValidator.java
  src/main/java/com/dinosaur/foodbowl/global/util/validator/image/ImageOrNull.java
  src/main/resources/config/application.yml
  src/test/java/com/dinosaur/foodbowl/FoodbowlApplicationTests.java
  src/test/java/com/dinosaur/foodbowl/domain/user/api/UserControllerTest.java
  src/test/java/com/dinosaur/foodbowl/domain/user/dao/UserRepositoryTest.java
  src/test/java/com/dinosaur/foodbowl/global/config/security/JwtTokenProviderTest.java
  src/test/java/com/dinosaur/foodbowl/global/util/thumbnail/file/ThumbnailFileDtoTest.java
  src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
Labels: 🗞️ chore, 🚨 Emergency

#64 Feature/#63 지정된 음식 카테고리로 수정한다.
  src/main/java/com/dinosaur/foodbowl/domain/category/entity/Category.java
  src/test/java/com/dinosaur/foodbowl/domain/category/entity/CategoryTest.java
Labels: 🔗 infra, ⛏️ refactor

#60 Feature/#18 프로필 정보를 가져오는 기능을 구현한다.
  src/docs/user/user.adoc
  src/main/java/com/dinosaur/foodbowl/domain/address/entity/Address.java
  src/main/java/com/dinosaur/foodbowl/domain/follow/dao/FollowRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/follow/entity/Follow.java
  src/main/java/com/dinosaur/foodbowl/domain/store/entity/Store.java
  src/main/java/com/dinosaur/foodbowl/domain/user/api/UserController.java
  src/main/java/com/dinosaur/foodbowl/domain/user/application/GetProfileService.java
  src/main/java/com/dinosaur/foodbowl/domain/user/application/signup/SignUpService.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dto/response/ProfileResponseDto.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dto/response/SignUpResponseDto.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/User.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/JwtTokenProvider.java
  src/test/java/com/dinosaur/foodbowl/domain/address/AddressTestHelper.java
  src/test/java/com/dinosaur/foodbowl/domain/category/CategoryTestHelper.java
  src/test/java/com/dinosaur/foodbowl/domain/post/PostTestHelper.java
  src/test/java/com/dinosaur/foodbowl/domain/store/StoreTestHelper.java
  src/test/java/com/dinosaur/foodbowl/domain/user/UserTestHelper.java
  src/test/java/com/dinosaur/foodbowl/domain/user/api/UserControllerTest.java
  src/test/java/com/dinosaur/foodbowl/domain/user/application/GetProfileServiceTest.java
  src/test/java/com/dinosaur/foodbowl/domain/user/dao/UserRepositoryTest.java
  src/test/java/com/dinosaur/foodbowl/global/config/security/JwtTokenProviderTest.java
  src/test/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailTestHelper.java
Labels: 🚀 feature, 🕋 backend

#66 Feature/#65 전체 카테고리를 추가한다.
  src/main/java/com/dinosaur/foodbowl/domain/category/entity/Category.java
Labels: 🚀 feature, 🕋 backend

#67 Feature/#19 팔로우 및 팔로우 취소 기능을 구현한다.
  src/docs/follow/follow.adoc
  src/main/java/com/dinosaur/foodbowl/domain/follow/api/FollowController.java
  src/main/java/com/dinosaur/foodbowl/domain/follow/application/FollowService.java
  src/main/java/com/dinosaur/foodbowl/domain/follow/dao/FollowRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/follow/entity/Follow.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/User.java
  src/main/java/com/dinosaur/foodbowl/global/error/ExceptionAdvice.java
  src/main/java/com/dinosaur/foodbowl/global/util/validator/follow/IsMeValidator.java
  src/main/java/com/dinosaur/foodbowl/global/util/validator/follow/NotMe.java
  src/test/java/com/dinosaur/foodbowl/IntegrationTest.java
  src/test/java/com/dinosaur/foodbowl/domain/follow/api/FollowControllerTest.java
  src/test/java/com/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
Labels: 📄 docs, 🚀 feature, 🕋 backend

#73 Feature/#16 로그인 및 로그아웃 기능을 구현한다.
  build.gradle
  src/docs/user/user.adoc
  src/main/java/com/dinosaur/foodbowl/domain/auth/api/AuthController.java
  src/main/java/com/dinosaur/foodbowl/domain/auth/application/AuthService.java
  src/main/java/com/dinosaur/foodbowl/domain/auth/application/TokenService.java
  src/main/java/com/dinosaur/foodbowl/domain/auth/dto/AuthFieldError.java
  src/main/java/com/dinosaur/foodbowl/domain/auth/dto/request/LoginRequestDto.java
  src/main/java/com/dinosaur/foodbowl/domain/auth/dto/request/SignUpRequestDto.java
  src/main/java/com/dinosaur/foodbowl/domain/auth/dto/response/SignUpResponseDto.java
  src/main/java/com/dinosaur/foodbowl/domain/user/api/UserController.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dao/UserFindDao.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dao/UserRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dto/response/ProfileResponseDto.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/role/Role.java
  src/main/java/com/dinosaur/foodbowl/global/config/redis/RedisConfiguration.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/SecurityConfiguration.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/dto/TokenValidationDto.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtConstants.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtToken.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtUserEntity.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtValidationType.java
  src/main/java/com/dinosaur/foodbowl/global/config/web/WebConfiguration.java
  src/main/java/com/dinosaur/foodbowl/global/error/BusinessException.java
  src/main/java/com/dinosaur/foodbowl/global/error/ErrorCode.java
  src/main/java/com/dinosaur/foodbowl/global/util/CookieUtils.java
  src/main/java/com/dinosaur/foodbowl/global/util/resolver/LoginUserId.java
  src/main/java/com/dinosaur/foodbowl/global/util/resolver/LoginUserIdArgumentResolver.java
  src/test/java/com/dinosaur/foodbowl/IntegrationTest.java
  src/test/java/com/dinosaur/foodbowl/domain/address/AddressTestHelper.java
  src/test/java/com/dinosaur/foodbowl/domain/auth/api/AuthControllerTest.java
  src/test/java/com/dinosaur/foodbowl/domain/auth/application/AuthServiceTest.java
  src/test/java/com/dinosaur/foodbowl/domain/auth/application/TokenServiceTest.java
  src/test/java/com/dinosaur/foodbowl/domain/follow/api/FollowControllerTest.java
  src/test/java/com/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
  src/test/java/com/dinosaur/foodbowl/domain/post/PostTestHelper.java
  src/test/java/com/dinosaur/foodbowl/domain/store/StoreTestHelper.java
  src/test/java/com/dinosaur/foodbowl/domain/user/UserTestHelper.java
  src/test/java/com/dinosaur/foodbowl/domain/user/api/UserControllerTest.java
  src/test/java/com/dinosaur/foodbowl/domain/user/application/GetProfileServiceTest.java
  src/test/java/com/dinosaur/foodbowl/domain/user/dao/UserFindDaoTest.java
  src/test/java/com/dinosaur/foodbowl/domain/user/dao/UserRepositoryTest.java
  src/test/java/com/dinosaur/foodbowl/global/config/security/JwtTokenProviderTest.java
  src/test/java/com/dinosaur/foodbowl/global/util/CookieUtilsTest.java
  src/test/java/com/dinosaur/foodbowl/global/util/thumbnail/ThumbnailTestHelper.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-cookies.snippet
  src/test/resources/org/springframework/restdocs/templates/response-cookies.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: 🚀 feature, 🕋 backend

#83 Feature/#81 Querydsl을 적용한다.
  build.gradle
Labels: 🚀 feature, 🕋 backend

#84 Feature/#82 유저, 게시글, 댓글 신고 관련 테이블을 설계한다.
  src/main/java/com/dinosaur/foodbowl/domain/blame/dao/BlameRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/blame/entity/Blame.java
Labels: 🚀 feature, 🕋 backend

#80 Feature/#79 닉네임 중복과 유효성을 검사하는 기능을 구현한다.
  src/docs/asciidoc/user/user.adoc
  src/main/java/com/dinosaur/foodbowl/domain/auth/api/AuthController.java
  src/main/java/com/dinosaur/foodbowl/domain/auth/application/AuthService.java
  src/main/java/com/dinosaur/foodbowl/domain/auth/dto/AuthFieldError.java
  src/main/java/com/dinosaur/foodbowl/domain/auth/dto/request/SignUpRequestDto.java
  src/main/java/com/dinosaur/foodbowl/domain/auth/dto/response/CheckResponseDto.java
  src/main/java/com/dinosaur/foodbowl/domain/auth/dto/response/SignUpResponseDto.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dao/UserRepository.java
  src/main/java/com/dinosaur/foodbowl/domain/user/dto/response/ProfileResponseDto.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/User.java
  src/main/java/com/dinosaur/foodbowl/domain/user/entity/embedded/Nickname.java
  src/main/java/com/dinosaur/foodbowl/global/config/security/SecurityConfiguration.java
  src/main/java/com/dinosaur/foodbowl/global/error/ExceptionAdvice.java
  src/test/java/com/dinosaur/foodbowl/domain/auth/api/AuthControllerTest.java
  src/test/java/com/dinosaur/foodbowl/domain/auth/application/AuthServiceTest.java
  src/test/java/com/dinosaur/foodbowl/domain/follow/dao/FollowRepositoryTest.java
  src/test/java/com/dinosaur/foodbowl/domain/user/UserTestHelper.java
  src/test/java/com/dinosaur/foodbowl/domain/user/application/GetProfileServiceTest.java
  src/test/java/com/dinosaur/foodbowl/domain/user/dao/UserRepositoryTest.java
Labels: 🚀 feature, 🕋 backend
